#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

PURGED="$dir/data/purge.list"

# CLEANUP SYSTEM
function cleanup {
echo ''
show_info 'What would you like to do? '
echo ''
echo '1. Remove unused pre-installed packages?'
echo '2. Remove old kernel(s)?'
echo '3. Remove orphaned packages?'
echo '4. Remove leftover configuration files?'
echo '5. Clean package cache?'
echo 'r. Return?'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Remove Unused Pre-installed Packages
1)
    echo 'Removing unused pre-installed applications...'
    echo ''
    echo 'Current package list:'
    echo ''
	old_IFS=$IFS      # save the field separator           
	IFS=$'\n'     # new field separator, the end of line           
	for package in $(cat $PURGED)
	do
	show_info 'Package: '$package
	show_info 'Purge? (Y)es, (N)o : ' && read REPLY1
	echo ''
	case $REPLY1 in
	[Yy]* )
		packages="$packages $(echo $package | cut -f1 -d"#" | xargs)"
		;; 
	* )
		;;
	esac
	done
	clear && echo 'Packages selected: ' $packages
    show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
    echo ''
    case $REPLY in
    # Positive action
    [Yy]* )
        show_info 'Requires root privileges:'
        sudo apt-get purge -y $packages
        show_success 'Done.'
        cleanup
        ;;
    # Negative action
    [Nn]* )
        clear && cleanup
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        cleanup
        ;;
    esac
    ;;
# Remove Old Kernel
2)
    echo 'Removing old Kernel(s)...'
    show_info 'Requires root privileges:'
    sudo dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | grep -v linux-libc-dev | xargs sudo apt-get -y purge
    show_success 'Done.'
    cleanup
    ;;
# Remove Orphaned Packages
3)
    echo 'Removing orphaned packages...'
    show_info 'Requires root privileges:'
    sudo apt-get autoremove -y
    show_success 'Done.'
    cleanup
    ;;
# Remove residual config files?
4)
    echo 'Removing leftover configuration files...'
    show_info 'Requires root privileges:'
    sudo dpkg --purge $(COLUMNS=200 dpkg -l | grep '^rc' | tr -s ' ' | cut -d ' ' -f 2)
    show_success 'Done.'
    cleanup
    ;;
# Clean Package Cache
5)
    echo 'Cleaning package cache...'
    show_info 'Requires root privileges:'
    sudo apt-get clean
    show_success 'Done.'
    cleanup
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && cleanup;;
esac
}
