#!/bin/bash

# CONFIG
function config {
echo ''
show_info 'What would you like to do? '
echo ''
echo '1. Show all startup applications?'
echo '2. Disable system crash dialogs (apport)?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Startup Applications
1)
    echo 'Changing display of startup applications...'
    show_info 'Requires root privileges:'
    sudo sed -i "s/NoDisplay=true/NoDisplay=false/g" /etc/xdg/autostart/*.desktop
    cd
    show_success 'Done.'
    config
    ;;
# Disable Apport
2)
    echo 'Disabling apport crash dialogs...'
    show_info 'Requires root privileges:'
    sudo sed -i "s/enabled=1/enabled=0/g" /etc/default/apport
    cd
    show_success 'Done.'
    config
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && config;;
esac
}
