#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

PPA_APPS="$dir/data/ppa_packs.list"

# INSTALL APPLICATIONS
function ppa_packs {
packages=''
# Install Favourite PPA Applications
echo ''
echo 'Installing selected favourite applications...'
echo ''
echo 'Current package list:'
echo ''
old_IFS=$IFS      # save the field separator           
IFS=$'\n'     # new field separator, the end of line           
for package in $(cat $PPA_APPS)
do
show_info 'Package: '$package
show_info 'Install? (Y)es, (N)o : ' && read REPLY1
echo ''
case $REPLY1 in
[Yy]* )
    packages="$packages $(echo $package | cut -f1 -d"#" | xargs)"
    ;; 
* )
    ;;
esac
done
clear && echo 'Packages selected: ' $packages
show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
IFS=$old_IFS     # restore default field separator
echo ''
case $REPLY in
# Positive action
[Yy]* ) 
    show_info 'Requires root privileges:'
    # Feel free to change the contents of 'favourites.list' in the data folder to whatever suits your preference.
    sudo apt-get install -y $packages
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    ppa_packs
    ;;
esac
}
